title: "Francois Bares"
description: "Personal website"
url: "https://francoisbares.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: "Francois Bares"